# -*- coding: utf-8 -*-
"""project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cl-aNldicgQM5duC9X6Uj3BRCzSMe1hV
"""

pip install SpeechRecognition pydub

import speech_recognition as sr
from pydub import AudioSegment

def convert_audio_to_text(audio_path):
    # Initialize recognizer
    recognizer = sr.Recognizer()

    # Check if audio format is MP3 and convert it to WAV
    if audio_path.endswith(".mp3"):
        audio = AudioSegment.from_mp3(audio_path)
        audio.export("converted_audio.wav", format="wav")
        audio_path = "converted_audio.wav"

    # Load the audio file (in WAV format)
    with sr.AudioFile(audio_path) as source:
        print("Processing audio...")
        audio_data = recognizer.record(source)  # Record the audio data

    try:
        # Recognize speech using Google Web Speech API
        print("Converting audio to text...")
        text = recognizer.recognize_google(audio_data)
        print("Transcription: " + text)
        return text
    except sr.UnknownValueError:
        print("Google Speech Recognition could not understand the audio.")
        return None
    except sr.RequestError as e:
        print(f"Could not request results from Google Speech Recognition service; {e}")
        return None

# Example usage:
audio_path = ""  # Replace with the path to your audio file
transcribed_text = convert_audio_to_text(audio_path)